### ISSUE TITLE
Can not run under python 2

### ISSUE THREAD

**Issue by tomosar** [sampsyo/clusterfutures#2]
Dear Sir,
I tested it under python3. Works great! 
But I don't understand under python 2. It has many problems with syntax.
Such as 
def submit(self, fun, *args, additional_setup_lines=[], **kwargs):
                                                      ^
SyntaxError: invalid syntax

print("job completed: %i" % jobid, file=sys.stderr)
                                           ^
SyntaxError: invalid syntax

Could you help me fix the code to run in python 2 ? 

This is due to when I loaded python3, there are many library conflicts with my program. So I only can work with python 2. 

Best regards,
Yen Nhi

**Comment by sampsyo** [comment]
Sorry; this is up to you! Pull requests to add simultaneous 2/3 compatibility would be gladly accepted, but I cannot commit to write the code. You might start with `from __future__ import print_function`.

**Comment by takluyver** [comment]
I'm going to close this - it's been four years since the request, it's increasingly unlikely that anyone is interested enough to backport it to Python 2, and I don't think there's a compelling case for us to maintain it even if someone did.

We can reopen it if someone (especially @sampsyo :slightly_smiling_face: ) thinks I've got this wrong, but from my perspective clusterfutures is a Python 3 package, and leaving this issue open is kind of misleading now.

**Comment by sampsyo** [comment]
Enthusiastically endorsed!
