### ISSUE TITLE
Add a SLURM cluster to the CI, via pytest-docker?

### ISSUE THREAD

**Issue by tcompa** [sampsyo/clusterfutures#20]
Hi there,
As mentioned in https://github.com/sampsyo/clusterfutures/pull/19#issuecomment-1360986506, we use pytest-docker within the CI of another project to spin up a SLURM cluster that we use for testing. This way we can run the actual commands (sbatch, squeue, ..), without having to mock them.

If there is some interest, I can draft a minimal PR to show how this could work for clusterfutures, and then let the mantainer(s) decide on whether they'd like to bring this in.

Of course there are downsides, e.g. longer testing times, additional dependencies (pytest-docker) and additional complexity in setting up the dev environment (you need docker installed and configured, if you want to run those tests locally).

**Comment by takluyver** [comment]
As things stand, clusterfutures is so simple that I'm inclined to stick to the lightweight test setup we have, rather than spinning up multiple docker containers to simulate a cluster.

It's undoubtedly better in some sense to test against a real-ish cluster, but there are real costs to all that complexity too - I've just spent half a day fixing the CI on another project after a dependency update. If clusterfutures grew more complexity, that trade-off might be worth it, but as it is, I don't think so.

**Comment by tcompa** [comment]
Perfectly clear.

For us it was sort of necessary to test some more complex features (notably submission as a different SLURM user). This is why have that in place and why I was suggesting it. But I fully understand the reasons for avoiding unnecessary complexity.
